version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Instalando dependencias...
  build:
    commands:
      - echo Compilando el proyecto...
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
