const empresas = [
  {
    nombreComercial: "Televisa",
    nombreOficial: "Grupo Televisa, S.A.B.",
    dueno: "Emilio Azcárraga Jean",
    sector: "Entretenimiento, Noticias, Comunicación",
    medios: ["TV", "Radio", "Web"],
    resumen:
      "Es uno de los grupos multimedia más grandes de América Latina, fundado en 1955.",
    mision:
      "Informar, entretener y conectar a millones de personas a través de contenidos innovadores.",
    vision: "Ser líderes en comunicación y entretenimiento en español.",
    enfoque:
      "Noticias nacionales e internacionales, deportes, espectáculos y entretenimiento.",
    sitioWeb: "https://www.televisa.com",
  },
  {
    nombreComercial: "TV Azteca",
    nombreOficial: "TV Azteca, S.A.B. de C.V.",
    dueno: "Ricardo Salinas Pliego",
    sector: "Televisión y medios digitales",
    medios: ["TV", "Web"],
    resumen:
      "Segunda cadena de televisión más grande de México con una amplia oferta de entretenimiento y noticias.",
    mision:
      "Producir contenido que informe y entretenga a la audiencia mexicana.",
    vision: "Ser referentes de calidad en producción audiovisual en América Latina.",
    enfoque: "Noticias y programación de entretenimiento.",
    sitioWeb: "https://www.tvazteca.com",
  },
  {
    nombreComercial: "Grupo Imagen",
    nombreOficial: "Grupo Imagen Multimedia",
    dueno: "Olegario Vázquez Raña",
    sector: "Televisión, radio y prensa",
    medios: ["TV", "Radio", "Web"],
    resumen:
      "Conjunto de medios que incluye Imagen Televisión y Radio Imagen, enfocado en noticias y entretenimiento.",
    mision: "Informar con objetividad y ofrecer contenidos de alta calidad.",
    vision: "Crecer como una opción sólida de comunicación nacional.",
    enfoque: "Noticias generales, deportes y espectáculos.",
    sitioWeb: "https://www.imagen.com.mx",
  },
  {
    nombreComercial: "Milenio",
    nombreOficial: "Grupo Multimedios",
    dueno: "Francisco Antonio González",
    sector: "Prensa escrita, digital y televisión",
    medios: ["Impreso", "Web", "TV"],
    resumen:
      "Medio reconocido por su cobertura noticiosa nacional con presencia en televisión y prensa.",
    mision: "Ofrecer información veraz, oportuna y relevante para la sociedad mexicana.",
    vision: "Consolidarse como medio de referencia nacional e internacional.",
    enfoque: "Noticias políticas, económicas, sociales y culturales.",
    sitioWeb: "https://www.milenio.com",
  },
  {
    nombreComercial: "El Universal",
    nombreOficial: "El Universal, Compañía Periodística Nacional, S.A. de C.V.",
    dueno: "Juan Francisco Ealy Ortiz",
    sector: "Prensa escrita y digital",
    medios: ["Impreso", "Web"],
    resumen: "Uno de los periódicos de mayor tradición en México, fundado en 1916.",
    mision: "Mantener informada a la sociedad con imparcialidad y objetividad.",
    vision: "Ser líder en periodismo multimedia en lengua española.",
    enfoque: "Política, economía, cultura y sociedad.",
    sitioWeb: "https://www.eluniversal.com.mx",
  },
  {
    nombreComercial: "Reforma",
    nombreOficial: "Grupo Reforma",
    dueno: "Alejandro Junco de la Vega",
    sector: "Prensa escrita y digital",
    medios: ["Impreso", "Web"],
    resumen:
      "Cadena de periódicos nacionales con enfoque crítico e independiente.",
    mision: "Impulsar la libertad de expresión y el periodismo de investigación.",
    vision: "Consolidar un periodismo profesional y plural en México.",
    enfoque: "Investigación política y económica.",
    sitioWeb: "https://www.reforma.com",
  },
  {
    nombreComercial: "Excélsior",
    nombreOficial: "Periódico Excélsior",
    dueno: "Grupo Imagen Multimedia",
    sector: "Prensa escrita y digital",
    medios: ["Impreso", "Web"],
    resumen: "Diario fundado en 1917 con cobertura de noticias nacionales e internacionales.",
    mision: "Informar con veracidad y profesionalismo.",
    vision: "Ser un referente periodístico para México.",
    enfoque: "Actualidad nacional, economía y cultura.",
    sitioWeb: "https://www.excelsior.com.mx",
  },
  {
    nombreComercial: "MVS Comunicaciones",
    nombreOficial: "MVS Comunicaciones",
    dueno: "Joaquín Vargas Guajardo",
    sector: "Radio, televisión y digital",
    medios: ["Radio", "TV", "Web"],
    resumen:
      "Grupo de comunicación que opera estaciones de radio y canales de televisión.",
    mision: "Brindar contenido de calidad que informe y entretenga.",
    vision: "Ser líderes en innovación en medios electrónicos.",
    enfoque: "Noticias, música y entretenimiento.",
    sitioWeb: "https://mvs.com",
  },
  {
    nombreComercial: "Grupo Fórmula",
    nombreOficial: "Grupo Fórmula",
    dueno: "Rogerio Azcárraga Madero",
    sector: "Radio y medios digitales",
    medios: ["Radio", "Web"],
    resumen:
      "Cadena de radio con cobertura nacional orientada a noticias y opinión.",
    mision: "Proporcionar espacios de análisis plural e informado.",
    vision: "Expandir su presencia en plataformas digitales.",
    enfoque: "Noticias de actualidad y programas de opinión.",
    sitioWeb: "https://www.radioformula.com.mx",
  },
];
export default empresas;
